- name: Copy postgreql backup script
  ansible.builtin.copy:
    src: '{{ role_path }}/files/postgresql-backup.sh'
    dest: /root/postgresql-backup.sh
    follow: yes

- name: Make script executable
  file:
    path: /root/postgresql-backup.sh
    owner: root
    group: root
    mode: 'u+x'

- name: Set up cron to back up PostgreSQL once a week
  ansible.builtin.cron:
    name: 'backup pg'
    minute: '0'
    hour: '0'
    weekday: '0'
    job: '/root/postgresql-backups.sh'
