- name: Build and compress assets
  shell: |
    podman exec -it audiopod-webapp npm run build-css

# dokku plugin:install https://github.com/dokku/dokku-copy-files-to-image.git  copy-files-to-image
# mkdir -p /home/dokku/{{app_name}}/DOKKU_FILES
# chown -R dokku:dokku /home/dokku/{{ app_name }}/DOKKU_FILES
# chmod -R +r /home/dokku/{{ app_name }}/DOKKU_FILES
# collectstatic locally to staticfiles
# ansible push files to DOKKU_FILES on server

- name: Push assets to S3
  shell: |
    podman exec -it \
    -e DJANGO_SETTINGS_MODULE=audiotrails.config.settings.deploy \
    -e SECRET_KEY="{{secret_key}}" \
    -e AWS_ACCESS_KEY_ID={{aws_access_key_id}} \
    -e AWS_S3_CUSTOM_DOMAIN={{aws_s3_custom_domain}} \
    -e AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}} \
    -e AWS_STORAGE_BUCKET_NAME={{aws_storage_bucket_name}} \
    audiopod-webapp ./manage.py collectstatic --noinput -v 3 -i css -i dev

- name: Push to Dokku
  shell: git push dokku main
