- name: Build and compress assets
  shell: |
    docker-compose -f {{compose_file}} run --rm \
    -e SECRET_KEY="{{secret_key}}" \
    -e DJANGO_SETTINGS_MODULE=audiotrails.config.settings.deploy \
    -e AWS_ACCESS_KEY_ID={{aws_access_key_id}} \
    -e AWS_S3_CUSTOM_DOMAIN={{aws_s3_custom_domain}} \
    -e AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}} \
    -e AWS_STORAGE_BUCKET_NAME={{aws_storage_bucket_name}} \
    assets yarn build

- name: Push assets to S3
  shell: |
    docker-compose -f {{compose_file}} run --rm \
    -e SECRET_KEY="{{secret_key}}" \
    -e DJANGO_SETTINGS_MODULE=audiotrails.config.settings.deploy \
    -e AWS_ACCESS_KEY_ID={{aws_access_key_id}} \
    -e AWS_S3_CUSTOM_DOMAIN={{aws_s3_custom_domain}} \
    -e AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}} \
    -e AWS_STORAGE_BUCKET_NAME={{aws_storage_bucket_name}} \
    django ./manage.py collectstatic --noinput -v 3 -i dev -i src

- name: Push to Dokku
  shell: git push dokku main
