repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 21.11b1
      hooks:
          - id: black
            language_version: python3.10
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.0a2
      hooks:
          - id: flake8
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.0
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
      rev: v1.0.5
      hooks:
          - id: python-bandit-vulnerability-check
            args: [--recursive, jcasts, --exclude, '**/tests/**.*', --skip, 'B410']
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.3.2'
      hooks:
          - id: prettier
            exclude: bundle.js|bundle.js.map|bundle.css|templates/|mockups/|node_modules/|README.md
    - repo: https://github.com/adamchainz/django-upgrade
      rev: '1.4.0'
      hooks:
          - id: django-upgrade
            args: [--target-version, '4.0'] # Replace with Django version
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.910'
      hooks:
          - id: mypy
            additional_dependencies:
                [
                    types-python-dateutil==2.8.2,
                    types-bleach==4.1.1,
                    types-requests==2.25.11,
                    types-Markdown==3.3.6,
                    types-attrs==19.1.0,
                ]
