repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
            exclude: ^assets/dist
          - id: end-of-file-fixer
            exclude: ^assets/dist
          - id: check-builtin-literals
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: destroyed-symlinks
          - id: detect-private-key
    - repo: local
      hooks:
          - id: rustywind
            name: rustywind Tailwind CSS class linter
            language: node
            additional_dependencies:
                - rustywind@0.21.0
            entry: rustywind
            args: [--write]
            files: ^templates
            types_or: [html]
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.16.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-conventional']
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.10.0
      hooks:
          - id: shellcheck
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.6.1"
      hooks:
          - id: ruff
            args: ["--fix"]
          - id: ruff-format
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.9.0
      hooks:
          - id: eslint
            files: ^assets
            exclude: ^assets/dist
    - repo: https://github.com/Riverside-Healthcare/djLint
      rev: v1.34.1
      hooks:
          - id: djlint-django
            args: ["--lint", "--reformat"]
            exclude: ^assets
    - repo: https://github.com/hadolint/hadolint
      rev: v2.13.0-beta
      hooks:
          - id: hadolint-docker
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
            args: [--py312]
    - repo: https://github.com/adamchainz/django-upgrade
      rev: "1.20.0"
      hooks:
          - id: django-upgrade
            args: [--target-version, "5.1"]
    - repo: https://github.com/abravalheri/validate-pyproject
      rev: v0.19
      hooks:
          - id: validate-pyproject
    - repo: https://github.com/python-poetry/poetry
      rev: 1.8.0
      hooks:
          - id: poetry-check
