repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: end-of-file-fixer
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: check-toml
          - id: check-yaml
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--settings-path, 'pyproject.toml']
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--target-version, 'py310']
            language_version: python3.10
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.2.4
      hooks:
          - id: python-safety-dependencies-check
            files: pyproject.toml
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
      rev: v1.0.6
      hooks:
          - id: python-bandit-vulnerability-check
            args: [--recursive, podtracker, --exclude, '**/tests/**.*', --skip, 'B410']
    - repo: https://github.com/rtts/djhtml
      rev: 'v1.5.0'
      hooks:
          - id: djhtml
            args: [--tabwidth, '4']
          - id: djjs
            exclude: bundle.js|bundle.js.map
          - id: djcss
            exclude: bundle.css
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.950'
      hooks:
          - id: mypy
            additional_dependencies:
                [
                    types-python-dateutil==2.8.2,
                    types-bleach==4.1.1,
                    types-requests==2.25.11,
                    types-Markdown==3.3.6,
                    types-attrs==19.1.0,
                ]
