repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.16.0
    hooks:
      - id: pyupgrade
        language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: ''
    hooks:
      - id: prettier
        exclude: bundle.js|bundle.js.map|bundle.css|templates/|mockups/|node_modules/|README.md'
