repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: end-of-file-fixer
            exclude: bundle.js|bundle.js.map|bundle.css
          - id: check-toml
          - id: check-yaml
          - id: check-json
            exclude: tsconfig.json
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            additional_dependencies: ['toml']
            args: [--settings-path, 'pyproject.toml']
    - repo: https://github.com/ambv/black
      rev: 22.6.0
      hooks:
          - id: black
            args: [--target-version, 'py310']
            language_version: python3.10
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies: [
                'flake8-bugbear==22.7.1',
                'flake8-print==5.0.0'
            ]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle
          additional_dependencies: ['toml']
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.3.0
      hooks:
          - id: python-safety-dependencies-check
            files: pyproject.toml
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
      rev: v1.0.6
      hooks:
          - id: python-bandit-vulnerability-check
            args: [--recursive, podtracker, --exclude, '**/tests/**.*', --skip, 'B410']
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
        - id: prettier
          files: \.(|ts|css)$
          exclude: bundle.js|bundle.js.map|bundle.css
    - repo: https://github.com/rtts/djhtml
      rev: 'v1.5.1'
      hooks:
          - id: djhtml
            args: [--tabwidth, '4']
