repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.16.0
    hooks:
      - id: pyupgrade
        # https://github.com/samuelcolvin/pydantic/issues/2597
        exclude: jcasts/podcasts/feed_parser.py
    language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'
    hooks:
      - id: prettier
        exclude: bundle.js|bundle.js.map|bundle.css|templates/|mockups/|node_modules/|README.md
