services:
    database:
        image: postgres:16.0-bookworm
        environment:
            POSTGRES_PASSWORD: password
steps:
    frontend:
        image: node:20-bookworm-slim
        commands:
            - npm install
            - npm run lint
        when:
            - event: pull_request
            - event: push
              branch: main
    backend:
        image: python:3.12.0-bookworm
        environment:
            - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
        commands:
            - pip install -r requirements-ci.txt
            - python -m ruff radiofeed
            - python -m djlint --lint templates/
            - xargs python -m nltk.downloader < nltk.txt
            - python -m pytest
        when:
            - event: pull_request
            - event: push
              branch: main
