- name: Configure dokku environment
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    dokku_packages_state: present
    dokku_manage_nginx: false
    dokku_daemon_install: false
  vars_files: vars.yml
  roles:
    - dokku_bot.ansible_dokku
    - configure
