- name: Configure environment variables
  become: yes
  hosts: all
  gather_facts: yes
  vars_files: vars.yml
  vars:
    dokku_packages_state: present
    dokku_daemon_install: false
    dokku_manage_nginx: false
    dokku_skip_key_file: true
  roles:
    - dokku_bot.ansible_dokku
    - configure
