- name: Run unit tests
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - tests

- name: Configure dokku environment
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    dokku_packages_state: present
  vars_files: vars.yml
  roles:
    - configure

- name: Deploy application
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - deploy
