- name: Run unit tests locally
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - tests

- name: Configure Dokku environment
  hosts: all
  become: yes
  gather_facts: yes
  vars_files: vars.yml
  roles:
    - configure

- name: Build static assets
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - build_assets

- name: Push static assets to Dokku and deploy
  hosts: all
  gather_facts: yes
  vars_files: vars.yml
  roles:
    - deploy
