- name: Run unit tests locally
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - tests

- name: Configure Dokku environment
  hosts: all
  become: yes
  gather_facts: yes
  vars_files: vars.yml
  roles:
    - configure

- name: Deploy application to Dokku
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - deploy
