version: '3.8'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  EMAIL_HOST: mailhog
  EMAIL_PORT: 1025
  REDIS_URL: redis://redis:6379/0
  SECRET_KEY: seekrit!
  TWITTER_ACCOUNT: casts_j

services:
  postgres:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    stop_grace_period: '3s'

  redis:
    image: redis:6.2.2-buster
    stop_grace_period: '3s'

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
      - '1025:1025'
    stop_grace_period: '3s'

  master: &master
    build:
      context: .
    image: jcasts/master:0.1
    restart: on-failure
    privileged: true
    tty: true
    stop_grace_period: '3s'

  watcher:
    <<: *master
    command: ['npm', 'run', 'watch']
    volumes:
      - .:/app
      - /app/node_modules

  django: &django
    <<: *master
    environment: *default-env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    entrypoint: /entrypoint

  webapp:
    <<: *django
    ports:
      - '80:8000'
    command: /start-webapp

  celeryworker:
    <<: *django
    command: /start-celeryworker

  celerybeat:
    <<: *django
    command: /start-celerybeat
    depends_on:
      - celeryworker
      - webapp

volumes:
  pg_data: {}
