version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0
  SECRET_KEY: seekrit

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: django.ci.dockerfile
    restart: on-failure
    privileged: true
    environment: *default-env
    depends_on:
      - postgres
    volumes:
      - .:/app

  assets:
    build:
      context: .
      dockerfile: assets.ci.dockerfile
    privileged: true
    volumes:
      - .:/app
      - /app/node_modules
