- name: Install Dokku
  hosts: server
  vars_files: ./vars.yaml
  gather_facts: true
  roles:
      - dokku_bot.ansible_dokku
  vars:
      appname: radiofeed
      dokku_hostname: "{{ domain }}"
      dokku_plugins:
          - name: postgres
            url: https://github.com/dokku/dokku-postgres.git
          - name: redis
            url: https://github.com/dokku/dokku-redis.git
          - name: letsencrypt
            url: https://github.com/dokku/dokku-letsencrypt.git
  tasks:
      - name: clear domains
        dokku_domains:
            app: "{{ appname }}"
            domains: "{{ appname }}.dokku.me"
            state: absent
      - name: add domain
        dokku_domains:
            app: "{{ appname }}"
            domains: "{{ domain }}"
      - name: create app
        dokku_clone:
            app: "{{ appname }}"
            repository: https://github.com/danjac/radiofeed-app
            version: main
            build: false
      - name: postgres:create
        dokku_service_create:
            name: radiofeed
            service: postgres
      - name: postgres:link
        dokku_service_link:
            app: "{{ appname }}"
            name: radiofeed
            service: postgres
      - name: redis:create
        dokku_service_create:
            name: radiofeed
            service: redis
      - name: redis:link
        dokku_service_link:
            app: "{{ appname }}"
            name: radiofeed
            service: redis
      - name: set letsencrypt email and request certificate
        block:
            - name: set letsencrypt email
              ansible.builtin.shell: dokku letsencrypt:set {{ appname }} email {{ letsencrypt_email }}

            - name: letsencrypt
              dokku_letsencrypt:
                  app: "{{ appname }}"
