- name: Setup Dokku
  become: yes
  hosts: all
  gather_facts: yes
  vars_files: vars.yml
  vars:
    dokku_version: 0.21.4
  roles:
    - dokku_bot.ansible_dokku

  tasks:
    - name: Set environment variables
      dokku_config:
        app: '{{ app_name }}'
        config:
          ADMIN_URL: '{{ admin_url }}'
