- name: Install Dokku
  hosts: server
  vars_files: ./vars.yaml
  gather_facts: true
  roles:
      - dokku_bot.ansible_dokku
  vars:
      appname: radiofeed
      dokku_plugins:
          - name: postgres
            url: https://github.com/dokku/dokku-postgres.git
          - name: redis
            url: https://github.com/dokku/dokku-redis.git
          - name: letsencrypt
            url: https://github.com/dokku/dokku-letsencrypt.git
  tasks:
      - name: set dokku app
        dokku_app:
            app: "{{ appname }}"
            state: present
      - name: clear domains
        dokku_domains:
            app: "{{ appname }}"
            domains: "{{ appname }}.dokku.me"
            state: absent
      - name: add domain
        dokku_domains:
            app: "{{ appname }}"
            domains: "{{ domain }}"
      - name: postgres:create
        dokku_service_create:
            name: radiofeed
            service: postgres
      - name: postgres:link
        dokku_service_link:
            app: "{{ appname }}"
            name: radiofeed
            service: postgres
      - name: redis:create
        dokku_service_create:
            name: radiofeed
            service: redis
      - name: redis:link
        dokku_service_link:
            app: "{{ appname }}"
            name: radiofeed
            service: redis
      - name: set letsencrypt email and request certificate
        block:
            - name: set letsencrypt email
              ansible.builtin.shell: dokku letsencrypt:set {{ appname }} email {{ letsencrypt_email }}

            - name: letsencrypt
              dokku_letsencrypt:
                  app: "{{ appname }}"
      - name: set environment variables
        dokku_config:
            app: "{{ appname }}"
            restart: false
            config:
                ADMIN_URL: "{{ admin_url }}"
                ADMINS: "{{ admins }}"
                ALLOWED_HOSTS: "{{ allowed_hosts }}"
                EMAIL_HOST: "{{ email_host }}"
                MAILGUN_API_KEY: "{{ mailgun_api_key }}"
                MAILGUN_API_URL: "{{ mailgun_api_url }}"
                SECRET_KEY: "{{ secret_key }}"
                SENTRY_URL: "{{ sentry_url }}"
      - name: create app
        dokku_clone:
            app: "{{ appname }}"
            repository: https://github.com/danjac/radiofeed-app
            version: main
            build: true
