# https://github.com/dokku/ansible-dokku#requirements
- name: Install dokku
  hosts: all
  become: yes
  roles:
    # - dokku_bot.ansible_dokku
    - geerlingguy.swap
  vars:
    swap_file_size_mb: '1048'
    dokku_version: 0.21.4
    dokku_users:
      - name: dokku
        username: dokku
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    # TBD: install postgres+redis plugins
    # install letsencrypt
    # set environ variables
    # dokku_config
