# https://github.com/dokku/ansible-dokku#requirements
- name: Install dokku
  hosts: all
  become: yes
  roles:
    - dokku_bot.ansible_dokku
    - geerlingguy.swap
  vars:
    swap_file_size_mb: '1048'
    dokku_version: 0.21.4
    dokku_users:
      - name: dokku
        username: dokku
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: redis
        url: https://github.com/dokku/dokku-redis.git

- name: Create dokku app
  hosts: all
  dokku_app:
    app: &appname radiofeed

- name: add domain
  hosts: all
  dokku_domains:
    app: *appname
    domains:
      - '{{ domain }}'

- name: Set environment variables
  hosts: all
  dokku_config:
    app: *appname
    restart: false
    config:
      BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-python
      DJANGO_SETTINGS_MODULE: radiofeed.config.settings.production
      DISABLE_COLLECTSTATIC: 1
      DOKKU_LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
      ADMIN_URL: '{{ admin_url }}'
      ADMINS: '{{ admins }}'
      ALLOWED_HOSTS: '{{ domain }}'
      SECRET_KEY: '{{ secret_key }}'
      AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
      AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
      AWS_S3_CUSTOM_DOMAIN: '{{ aws_s3_custom_domain }}'
      AWS_STORAGE_BUCKET_NAME: '{{ aws_storage_bucket_name }}'
      MAILGUN_API_KEY: '{{ mailgun_api_key }}'
      MAILGUN_SENDER_DOMAIN: '{{ mailgun_sender_domain }}'
      SENTRY_URL: '{{ sentry_url }}'
# TBD:
# dokku letsencrypt:cron-job --add
# dokku ps:scale myapp worker=1
# dokku ps:scale myapp beat=1
