- name: Setup Dokku
  become: yes
  hosts: all
  gather_facts: yes
  vars_files: vars.yml
  vars:
    dokku_version: 0.21.4
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: redis
        url: https://github.com/dokku/dokku-redis.git
  roles:
    - dokku_bot.ansible_dokku
  tasks:
    - name: Add domain
      dokku_domains:
        app: '{{ app_name }}'
        domains: '{{ domain_name }}'

    - name: Clone repo
      dokku_clone:
        app: '{{ app_name }}'
        repository: https://github.com/danjac/radiofeed.git

    - name: Set environment variables
      dokku_config:
        app: '{{ app_name }}'
        restart: false
        config:
          ADMIN_URL: '{{ admin_url }}'
          ADMINS: '{{ admins }}'
          AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
          AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
          AWS_STORAGE_BUCKET_NAME: '{{ aws_storage_bucket_name }}'
          AWS_S3_CUSTOM_DOMAIN: '{{ aws_s3_custom_domain }}'
          BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-python
          ALLOWED_HOSTS: '{{ domain_name }}'
          DISABLE_COLLECTSTATIC: '1'
          DJANGO_SETTINGS_MODULE: radiofeed.config.settings.production
          DOKKU_LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
          GOOGLE_TRACKING_ID: '{{ google_tracking_id }}'
          MAILGUN_API_KEY: '{{ mailgun_api_key }}'
          MAILGUN_SENDER_DOMAIN: '{{ mailgun_sender_domain }}'
          SECRET_KEY: '{{ secret_key }}'
          SENTRY_URL: '{{ sentry_url }}'
