# ansible-galaxy collection install community.docker
- name: Update and upgrade apt packages
  become: yes
  hosts: all
  vars_files: vars.yml
  gather_facts: no
  roles:
    - pg-vacuum
    - pg-backup
    - docker
    - apt-update
    - geerlingguy.swap
