- name: Update and upgrade apt packages, install swap memory
  become: yes
  hosts: all
  vars_files: vars.yml
  gather_facts: no
  roles:
    # - pg-backup
    # - clear-sessions
    # - pg-vacuum
    - docker
    - apt-update
    - geerlingguy.swap
