# ansible-galaxy collection install community.docker
- name: Update and upgrade apt packages
  become: yes
  hosts: all
  gather_facts: no
  roles:
    - docker
    - apt-update
    - geerlingguy.swap
