[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "radiofeed"
requires-python = ">=3.10"
version = "0"
license = {text = "MIT"}
authors = [
    {name ="Dan Jacob", email = "danjac2018@gmail.com"}
]
dependencies = [
    "Django",
    "Markdown",
    "Pillow",
    "attrs",
    "bleach",
    "brotli",
    "dj-database-url",
    "django-allauth",
    "django-anymail",
    "django-cacheops",
    "django-extensions",
    "django-fast-update",
    "django-health-check",
    "django-htmx",
    "django-model-utils",
    "django-object-actions",
    "django-permissions-policy",
    "django-redis",
    "django-widget-tweaks",
    "gunicorn",
    "hiredis",
    "httpx",
    "lxml",
    "nltk",
    "numpy",
    "pandas",
    "psutil",
    "psycopg2-binary",
    "python-dateutil",
    "python-decouple",
    "redis",
    "scikit-learn",
    "scipy",
    "sentry-sdk",
    "whitenoise",
]

[project.optional-dependencies]
dev = [
    "bandit[toml]",
    "coverage",
    "django-browser-reload",
    "django-coverage-plugin",
    "django-debug-toolbar",
    "djlint",
    "faker",
    "flake8",
    "flake8-bugbear",
    "flake8-comprehensions",
    "flake8-debugger",
    "flake8-deprecated",
    "flake8-print",
    "flake8-pyproject",
    "ipython",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-django",
    "pytest-icdiff",
    "pytest-mock",
    "pytest-mypy",
    "pytest-randomly",
    "pytest-sugar",
    "pytest-xdist",
    "types-bleach",
    "types-markdown",
    "types-python-dateutil",
]

[tool.isort]
default_section = "THIRDPARTY"
known_first_party = "radiofeed"
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
lines_between_types = 1
group_by_package = true
order_by_type = true
line_length = 88
include_trailing_comma = true
multi_line_output = 3
add_imports = "from __future__ import annotations"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "radiofeed.settings.test"
addopts = "-v -x --ff --reuse-db -p no:warnings --tb=short --mypy --cov --no-cov-on-fail --cov-fail-under=100 --cov-report=term-missing"
testpaths = "radiofeed"

[tool.coverage.run]
source=["radiofeed", "templates"]
omit=[
    "**/factories.py",
    "**/wsgi.py",
    "*/migrations/*",
    "*/nltk/*",
    "*/settings/*",
    "*/static/*",
    "*/tests/*",
]

plugins = [
    "django_coverage_plugin"
]

[tool.django_coverage_plugin]
template_extensions = ["html"]


[tool.mypy]
python_version = "3.11"
check_untyped_defs = false
ignore_missing_imports = true
show_error_codes = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = false
warn_redundant_casts = false
warn_unused_configs = false
warn_unreachable = true

[[tool.mypy.overrides]]
module="*.tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module="*.migrations.*"
ignore_errors = true

[tool.pyright]
reportOptionalMemberAccess = false
reportGeneralTypeIssues = false
reportMissingTypeStubs = false

[tool.bandit]
exclude_dirs = ["**/tests/**.*"]
skips = ["B410"]

[tool.djlint]
ignore = "H030,H031,H017,H021"

[tool.pydocstyle]
ignore = [
    "D100",
    "D104",
    "D106",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D401",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]

[tool.flake8]
ignore = [
    "E203",
    "E266",
    "E501",
    "W503",
    "E231",
    "E701",
    "C812",
    "D100",
    "Q000",
    "S101"
]
max-line-length = 88
max_complexity = 10
