[tool.poetry]
name = "radiofeed-app"
version = "0.1.0"
description = "Podcast aggregator app"
authors = ["Dan Jacob <danjac2018@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">3.9,<3.11"
Brotli = "^1.0.9"
Markdown = "^3.3.7"
Werkzeug = "^2.1.2"
bleach = "^5.0.0"
dj-database-url = "^0.5.0"
django-allauth = "^0.50.0"
django-anymail = "^8.5"
django-environ = "^0.8.1"
django-extensions = "^3.1.5"
django-htmx = "^1.11.0"
django-model-utils = "^4.2.0"
django-object-actions = "^4.0.0"
django-permissions-policy = "^4.10.0"
django-postgres-metrics = "^0.13.1"
django-ratelimit = "^3.0.1"
django-redis = "^5.2.0"
django-split-settings = "^1.1.0"
django-widget-tweaks = "^1.4.12"
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
ipython = "^8.3.0"
lxml = "^4.8.0"
nltk = "^3.7"
numpy = "^1.22.3"
pandas = "^1.4.2"
psutil = "^5.9.0"
psycopg2-binary = "^2.9.3"
python-dateutil = "^2.8.2"
redis = "^4.3.1"
requests = "^2.27.1"
scikit-learn = "^1.0.2"
scipy = "^1.8.0"
sentry-sdk = "^1.5.12"
whitenoise = "^6.1.0"
django-fast-update = "^0.2.0"
attrs = "^21.4.0"
django-modeltranslation = "^0.18.2"
Django = "^4.1"
django-cacheops = "^6.1"

[tool.poetry.dev-dependencies]
Faker = "^13.11.0"
coverage = "^6.3.2"
django-debug-toolbar = "^3.4.0"
honcho = "^1.1.0"
factory-boy = "^3.2.1"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"
pytest-forked = "^1.4.0"
pytest-mock = "^3.7.0"
pytest-randomly = "^3.11.0"
pytest-xdist = "^2.5.0"
types-requests = "^2.28.0"
types-bleach = "^5.0.2"
types-Markdown = "^3.3.29"
types-python-dateutil = "^2.8.18"
mypy = "^0.961"
django-silk = "^5.0.1"
pytest-sugar = "^0.9.5"
pytest-flake8 = "^1.1.1"
pytest-mypy = "^0.9.1"
flake8 = "^4.0.1"
pytest-icdiff = "^0.5"
django-coverage-plugin = "^2.0.3"
coverage-badge = "^1.1.0"
flake8-print = "^5.0.0"
rich = "^12.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pydocstyle]
ignore = [
    "D100",
    "D104",
    "D106",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D401",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]

[tool.isort]
default_section="THIRDPARTY"
known_first_party="radiofeed"
sections=[
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
lines_between_types=1
group_by_package=true
order_by_type=true
line_length = 88
include_trailing_comma=true
multi_line_output=3
add_imports = "from __future__ import annotations"

[tool.coverage.run]
source=["radiofeed"]
omit=[
    "**/factories.py",
    "*/migrations/*",
    "*/config/*",
    "*/nltk/*",
    "*/tests/*",
]

plugins = [
    "django_coverage_plugin"
]

[tool.django_coverage_plugin]
template_extensions = ["html"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="radiofeed.config.settings.test"
addopts="-v -x --ff --reuse-db -p no:warnings --tb=short --mypy --flake8 --cov --no-cov-on-fail --cov-fail-under=100"
testpaths="radiofeed"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = false
ignore_missing_imports = true
show_error_codes = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = false
warn_redundant_casts = false
warn_unused_configs = false
warn_unreachable = true

[[tool.mypy.overrides]]
module="*.tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module="*.migrations.*"
ignore_errors = true

[tool.pyright]
reportGeneralTypeIssues = false
reportOptionalMemberAccess = false

[tool.bandit]
exclude_dirs = ["**/tests/**.*"]
skips = ["B410"]
