[tool.poetry]
name = "radiofeed-app"
version = "0.1.0"
description = "Podcast aggregator app"
authors = ["Dan Jacob <danjac2018@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">3.9,<3.11"
Brotli = "^1.0.9"
Django = "^4.0.4"
Markdown = "^3.3.7"
Werkzeug = "^2.1.2"
bleach = "^5.0.0"
dj-database-url = "^0.5.0"
django-allauth = "^0.50.0"
django-anymail = "^8.5"
django-cachalot = "^2.5.1"
django-environ = "^0.8.1"
django-extensions = "^3.1.5"
django-health-check = "^3.16.5"
django-htmx = "^1.11.0"
django-model-utils = "^4.2.0"
django-object-actions = "^4.0.0"
django-permissions-policy = "^4.10.0"
django-postgres-metrics = "^0.13.1"
django-ratelimit = "^3.0.1"
django-redis = "^5.2.0"
django-split-settings = "^1.1.0"
django-widget-tweaks = "^1.4.12"
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
ipython = "^8.3.0"
lxml = "^4.8.0"
nltk = "^3.7"
numpy = "^1.22.3"
pandas = "^1.4.2"
psutil = "^5.9.0"
psycopg2-binary = "^2.9.3"
python-dateutil = "^2.8.2"
redis = "^4.3.1"
requests = "^2.27.1"
scikit-learn = "^1.0.2"
scipy = "^1.8.0"
sentry-sdk = "^1.5.12"
whitenoise = "^6.1.0"
rq = "^1.10.1"
django-rq = "^2.5.1"

[tool.poetry.dev-dependencies]
Faker = "^13.11.0"
coverage = "^6.3.2"
django-debug-toolbar = "^3.4.0"
honcho = "^1.1.0"
factory-boy = "^3.2.1"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"
pytest-forked = "^1.4.0"
pytest-mock = "^3.7.0"
pytest-randomly = "^3.11.0"
pytest-xdist = "^2.5.0"
django-stubs = "^1.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
default_section="THIRDPARTY"
known_first_party="radiofeed"
sections=[
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
lines_between_types=1
group_by_package=true
order_by_type=true
line_length = 88
include_trailing_comma=true
multi_line_output=3

[tool.coverage.run]
source=["radiofeed"]
omit=[
    "**/factories.py",
    "*/migrations/*",
    "*/tests/*",
    "*/settings/*",
    "*/wsgi.py",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="radiofeed.settings.test"
addopts="-v -x --ff --reuse-db -p no:warnings --tb=short"
testpaths="radiofeed"

[mypy]
python_version = 3.10
check_untyped_defs = false
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = false
warn_redundant_casts = false
warn_unused_configs = false
warn_unreachable = true

plugins = ["mypy_django_plugin.main"]

[[tool.mypy.overrides]]
module="*.tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module="*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "radiofeed.settings.test"
