[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "radiofeed-app"
version = "0"
description = "Podcast aggregator app"
authors = ["Dan Jacob <danjac2018@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.4"
Pillow = "^9.3.0"
attrs = "^22.1.0"
bleach = "^5.0.1"
dj-database-url = "^1.2.0"
django-allauth = "^0.51.0"
django-cacheops = "^6.1"
django-environ = "^0.9.0"
django-extensions = "^3.2.1"
django-fast-update = "^0.2.1"
django-htmx = "^1.13.0"
django-model-utils = "^4.3.1"
django-modeltranslation = "^0.18.7"
django-object-actions = "^4.1.0"
django-permissions-policy = "^4.14.0"
django-redis = "^5.2.0"
django-widget-tweaks = "^1.4.12"
hiredis = "^2.1.0"
lxml = "^4.9.2"
Markdown = "^3.4.1"
nltk = "^3.8"
numpy = "^1.24.0"
pandas = "^1.5.2"
psycopg2-binary = "^2.9.5"
python-dateutil = "^2.8.2"
redis = "^4.4.0"
requests = "^2.28.1"
scikit-learn = "^1.2.0"
scipy = "^1.9.3"
user-agent = "^0.1.10"
whitenoise = "^6.2.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
django-debug-toolbar = "^3.8.1"
djhtml = "^1.5.2"
honcho = "^1.1.0"
ipython = "^8.7.0"
isort = "^5.11.3"

[tool.poetry.group.ci.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-icdiff = "^0.6"
pytest-mock = "^3.10.0"
mypy = "^0.991"
pytest-mypy = "^0.10.3"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.6"
pytest-xdist = "^3.1.0"
faker = "^15.3.4"
coverage = "^7.0.0"
django-coverage-plugin = "^3.0.0"
djlint = "^1.19.9"
flake8 = "^6.0.0"
flake8-bugbear = "^22.12.6"
flake8-comprehensions = "^3.10.1"
flake8-debugger = "^4.1.2"
flake8-deprecated = "^2.0.1"
flake8-print = "^5.0.0"
types-bleach = "^5.0.3.1"
types-markdown = "^3.4.2.1"
types-python-dateutil = "^2.8.19.5"
types-requests = "^2.28.11.6"
bandit = {extras = ["toml"], version = "^1.7.4"}
pytest-env = "^0.8.1"

[tool.poetry.group.prod.dependencies]
brotli = "^1.0.9"
gunicorn = "^20.1.0"
sentry-sdk = "^1.12.1"
django-anymail = "^9.0"

[tool.pydocstyle]
ignore = [
    "D100",
    "D104",
    "D106",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D401",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]


[tool.isort]
default_section="THIRDPARTY"
known_first_party="radiofeed"
sections=[
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
lines_between_types=1
group_by_package=true
order_by_type=true
line_length = 88
include_trailing_comma=true
multi_line_output=3
add_imports = "from __future__ import annotations"

[tool.coverage.run]
source=["radiofeed", "templates"]
omit=[
    "**/factories.py",
    "*/migrations/*",
    "*/config/*",
    "*/nltk/*",
    "*/static/*",
    "*/tests/*",
]

plugins = [
    "django_coverage_plugin"
]

[tool.django_coverage_plugin]
template_extensions = ["html"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="radiofeed.config.settings"
addopts="-v -x --ff --reuse-db -p no:warnings --tb=short --mypy --cov --no-cov-on-fail --cov-fail-under=100 --cov-report=term-missing"
testpaths="radiofeed"
env=[
    "ENVIRONMENT=testing",
]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = false
ignore_missing_imports = true
show_error_codes = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = false
warn_redundant_casts = false
warn_unused_configs = false
warn_unreachable = true

[[tool.mypy.overrides]]
module="*.tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module="*.config.*"
ignore_errors = true

[[tool.mypy.overrides]]
module="*.migrations.*"
ignore_errors = true

[tool.pyright]
reportGeneralTypeIssues = false
reportOptionalMemberAccess = false

[tool.bandit]
exclude_dirs = ["**/tests/**.*"]
skips = ["B410"]

[tool.djlint]
ignore = "H030,H031,H017,H021"
