[tool.poetry]
name = "jcasts"
version = "0.1.0"
description = ""
authors = ["Dan Jacob <danjac2018@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.9.3"
bleach = "^3.3.0"
cryptography = ">=3.2"
dj-database-url = "^0.5.0"
Django = "^3.2.4"
django-allauth = "^0.44.0"
django-anymail = {extras = ["mailgun"], version = "^8.4"}
django-environ = "^0.4.5"
django-extensions = "^3.1.3"
django-model-utils = "^4.1.1"
django-permissions-policy = "^4.1.0"
django-redis = "^5.0.0"
django-split-settings = "^1.0.1"
django-widget-tweaks = "^1.4.8"
feedparser = "^6.0.6"
future = "^0.18.2"
gunicorn = "^20.1.0"
html5lib = "^1.1"
httptools = "^0.2.0"
ipython = "^7.24.1"
lxml = "^4.6.3"
nltk = "^3.6.2"
pandas = "^1.2.4"
psycopg2-binary = "^2.9.1"
pyOpenSSL = "^20.0.1"
python-dateutil = "^2.8.1"
pytz = "^2021.1"
redis = "^3.5.3"
sentry-sdk = "^1.1.0"
sklearn = "^0.0"
Unidecode = "^1.2.0"
whitenoise = {extras = ["brotli"], version = "^5.2.0"}
django-htmx = "^1.1.0"
django-rq = "^2.4.1"
django-ratelimit = "^3.0.1"
Markdown = "^3.3.4"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
factory-boy = "^3.2.0"
Werkzeug = "^2.0.1"
pytest = "^6.2.4"
pytest-django = "^4.4.0"
pytest-xdist = "^2.3.0"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
pytest-randomly = "^3.8.0"
fakeredis = "^1.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
