[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Dan Jacob <danjac2018@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^8.2.0"
beautifulsoup4 = "^4.9.3"
bleach = "^3.3.0"
boto3 = "^1.17.54"
celery = "^5.0.5"
cryptography = ">=3.2"
dj-database-url = "^0.5.0"
Django = "^3.2"
django-allauth = "^0.44.0"
django-anymail = {extras = ["mailgun"], version = "^8.2"}
django-celery-beat = "^2.2.0"
django-celery-email = "^3.0.0"
django-environ = "^0.4.5"
django-extensions = "^3.1.3"
django-model-utils = "^4.1.1"
django-redis = "^4.12.1"
django-storages = "^1.11.1"
django-turbo-allauth = "^0.0.9"
django-turbo-response = "^0.0.48"
django-widget-tweaks = "^1.4.8"
factory-boy = "^3.2.0"
future = "^0.18.2"
gunicorn = "^20.1.0"
html5lib = "^1.1"
httptools = "^0.1.1"
ipython = "^7.22.0"
jedi = "0.17.2"
lxml = "^4.6.3"
nltk = "^3.6.2"
pandas = "^1.2.4"
psycopg2-binary = "^2.8.6"
pydantic = "^1.8.1"
pyOpenSSL = "^20.0.1"
python-dateutil = "^2.8.1"
pytz = "^2021.1"
redis = "^3.5.3"
sentry-sdk = "^1.0.0"
sklearn = "^0.0"
sorl-thumbnail = "^12.7.0"
Unidecode = "^1.2.0"
Werkzeug = "^1.0.1"

[tool.poetry.dev-dependencies]
django-silk = "^4.1.0"
pytest = "^6.2.3"
pytest-asyncio = "^0.15.0"
pytest-cov = "^2.11.1"
pytest-django = "^4.2.0"
pytest-mock = "^3.5.1"
pytest-randomly = "^3.7.0"
pytest-xdist = "^2.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
