databases:
  - name: podtracker
    databaseName: podtracker
    user: podtracker

services:
  - type: redis
    name: redis
    plan: starter
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: web
    name: app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn podtracker.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: DATABASE_URL
        fromDatabase:
          name: podtracker
          property: connectionString
      - key: REDIS_URL
        fromService:
            type: redis
            name: redis
            property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: "podtracker.settings.production"
  - type: worker
    name: worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py rqworker mail default feeds feeds:frequent feeds:sporadic"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: DATABASE_URL
        fromDatabase:
          name: podtracker
          property: connectionString
      - key: REDIS_URL
        fromService:
            type: redis
            name: redis
            property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "podtracker.settings.production"
