- name: Copy postgreql vacuum script
  ansible.builtin.copy:
    src: '{{ role_path }}/files/pg-vacuum.sh'
    dest: /root/pg-vacuum.sh
    follow: yes

- name: Make script executable
  file:
    path: /root/pg-vacuum.sh
    owner: root
    group: root
    mode: 'u+x'

- name: Run vacuum
  shell: /root/pg-vacuum.sh
