apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2021-04-25T12:15:59Z'
  labels:
    app: audiopod
  name: audiopod
spec:
  securityContext:
    seLinuxOptions: {}
    runAsGroup: 1000
    runAsUser: 1000
  containers:
    - name: postgresql
      command:
        - docker-entrypoint.sh
      args:
        - postgres
      env:
        - name: LANG
          value: en_US.utf8
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PG_MAJOR
          value: '11'
        - name: PG_VERSION
          value: 11.8-1.pgdg90+1
      image: docker.io/library/postgres:11.8
      ports:
        - containerPort: 5432
          hostPort: 37647
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: audiotrails-db-host
      workingDir: /

    - name: mailhog
      command:
        - MailHog
      image: docker.io/mailhog/mailhog:v1.0.0
      ports:
        - containerPort: 8025
          hostPort: 8025
          protocol: TCP
        - containerPort: 1025
          hostPort: 42811
          protocol: TCP
      resources: {}
      workingDir: /home/mailhog

    - name: redis
      command:
        - docker-entrypoint.sh
      args:
        - redis-server
      image: docker.io/library/redis:6.2.2-buster
      ports:
        - containerPort: 6379
          hostPort: 40495
          protocol: TCP
      resources: {}
      workingDir: /data

    - name: celeryworker
      command:
        - /entrypoint
      args:
        - /start-celeryworker
      envFrom:
        - configMapRef:
            name: audiopod-configmap
      image: localhost/audiotrails:latest
      # imagePullPolicy: Never
      resources: {}
      volumeMounts:
        - mountPath: /app
          name: audiotrails-host
      workingDir: /app

    - name: celerybeat
      command:
        - /entrypoint
      args:
        - /start-celerybeat
      envFrom:
        - configMapRef:
            name: audiopod-configmap
      image: localhost/audiotrails:latest
      #imagePullPolicy: Never
      resources: {}
      volumeMounts:
        - mountPath: /app
          name: audiotrails-host
      workingDir: /app

    - name: watchman
      command:
        - /start-watchman
      envFrom:
        - configMapRef:
            name: audiopod-configmap
      image: localhost/audiotrails:latest
      # imagePullPolicy: Never
      resources: {}
      volumeMounts:
        - mountPath: /app
          name: audiotrails-host
      workingDir: /app

    - name: webapp
      command:
        - /entrypoint
      args:
        - /start-webapp
      envFrom:
        - configMapRef:
            name: audiopod-configmap
      image: localhost/audiotrails:latest
      # imagePullPolicy: Never
      ports:
        - containerPort: 8000
          hostPort: 8000
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /app
          name: audiotrails-host
      workingDir: /app

  dnsConfig: {}
  restartPolicy: Never
  volumes:
    - hostPath:
        path: .
        type: Directory
      name: audiotrails-host
    - hostPath:
        path: ./db
        type: DirectoryOrCreate
      name: audiotrails-db-host
status: {}
