- name: Generate Docker swarm config file
  vars:
      database_ip: "{{ hostvars[groups['databases'][0]].private_ip }}"
  ansible.builtin.template:
    src: templates/stack.yml.j2
    dest: "{{ project_dir }}/stack.yml"
    mode: "u+r"

- name: Initialize Docker swarm
  community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ hostvars[groups['managers'][0]].private_ip  }}"
  register: swarm
