- name: Generate Docker swarm config file
  vars:
      database_ip: "{{ hostvars[groups['databases'][0]].private_ip }}"
  ansible.builtin.template:
    src: templates/stack.yml.j2
    dest: "{{ project_dir }}/stack.yml"
    mode: "u+rw,g+rw"

- name: Add deploy script
  ansible.builtin.template:
    src: templates/deploy_stack.sh.j2
    dest: "/home/{{ user }}/deploy_stack.sh"
    mode: "u+x,g+x"

- name: Initialize Docker swarm
  community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ hostvars[groups['managers'][0]].private_ip  }}"
  register: swarm

- name: Deploy stack
  ansible.builtin.shell:
    cmd: ./deploy_stack.sh
