- name: Set up backup auth
  shell: |
    dokku postgres:backup-deauth {{ app_db_name }} &&
    dokku postgres:backup-auth {{ app_db_name }} {{ aws_access_key_id}} {{ aws_secret_access_key }}

- name: Run backup to AWS
  shell: |
    dokku postgres:backup {{ app_db_name }} {{ aws_backups_bucket_name }}
