- name: Create .kube dir for user
  ansible.builtin.file:
      path: /home/{{ deploy_user }}/.kube
      state: directory
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: 0700

- name: Copy kubeconfig to user home dir
  ansible.builtin.copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /home/{{ deploy_user }}/.kube/config
      remote_src: true
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: "u+rw"

- name: Create deploy.sh script for CI/CD deployments
  ansible.builtin.template:
      src: deploy.sh.j2
      dest: /home/{{ deploy_user }}/deploy.sh
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: "u+x"
