- name: Install application
  hosts: webservers
  vars_files:
      - ./vars/dokku.yml
      - ./vars/django.yml
      - ./vars/users.yml
  gather_facts: true
  roles:
      - dokku_bot.ansible_dokku
  tasks:
      - import_tasks: ./tasks/app.yml
      - import_tasks: ./tasks/services.yml
      - import_tasks:
            ./tasks/letsencrypt.yml
            # replace letsencrypt with traefik
      # - import_tasks: ./tasks/traefik.yml
      - import_tasks: ./tasks/config.yml
      - import_tasks: ./tasks/build.yml
      - import_tasks: ./tasks/default_site.yml
      - import_tasks: ./tasks/superuser.yml
      - import_tasks: ./tasks/fixtures.yml
