- name: Install Letsencrypt
  hosts: server
  vars_files:
      - ./vars/common.yaml
      - ./vars/secrets.yaml
  gather_facts: true
  roles:
      - dokku_bot.ansible_dokku
  tasks:
      - import_tasks: ./tasks/letsencrypt.yaml
