- name: Set variables for the deployment
  ansible.builtin.set_fact:
      kubeconfig: "/home/{{ ansible_user }}/.kube/config"
      cronjobs:
          - {
                name: "parse-feeds",
                schedule: "*/6 * * * *", # Every 6 minutes
                command: "./manage.py parse_feeds",
            }
          - {
                name: "create-recommendations",
                schedule: "20 15 * * *", # 3:20 PM
                command: "./manage.py create_recommendations",
            }
          - {
                name: "send-recommendations",
                schedule: "45 18 * * 1", # 6:45 PM every Monday
                command: "./manage.py send_recommendations",
            }
          - {
                name: "fetch-itunes-top-chart",
                schedule: "15 7 * * *", # 7:15 AM
                command: "./manage.py fetch_itunes_chart",
            }

          - {
                name: "clear-sessions",
                schedule: "5 5 * * *", # 5:05 AM
                command: "./manage.py clearsessions",
            }

- name: Label the agent nodes
  ansible.builtin.shell: |
      kubectl label nodes {{ hostvars[item].node_name }} role=agent
  loop: "{{ groups['agents'] }}"
  environment:
      KUBECONFIG: "{{ kubeconfig }}"

- name: Get the current image from Kubernetes
  ansible.builtin.command: kubectl get deployment django-app -n default -o jsonpath="{.spec.template.spec.containers[0].image}"
  register: current_image_result
  changed_when: false
  failed_when: false # Don't fail if deployment doesn't exist
  environment:
      KUBECONFIG: "{{ kubeconfig }}"

- name: Set default image if no current deployment exists
  ansible.builtin.set_fact:
      current_image: "{{ current_image_result.stdout if current_image_result.stdout else docker_image + ':main' }}"

- name: Apply spec files
  vars:
      database_ip: "{{ hostvars[groups['database'][0]].private_ip }}"
      database_url: "postgresql://postgres:{{ postgres_password }}@{{ database_ip }}:5432/postgres"
      redis_url: "redis://{{ database_ip }}:6379/0"
      replicas: "{{ groups['agents']|length }}"

  ansible.builtin.command: >
      kubectl apply -f -
  args:
      stdin: "{{ lookup('template', item + '.j2') }}"
  loop:
      - deployment.yaml
      - cronjobs.yaml
      - service.yaml
      - configmap.yaml
      - secrets.yaml

  environment:
      KUBECONFIG: "{{ kubeconfig }}"

- name: Add scripts to the deployment
  ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "{{ item }}"
      mode: "u+x"
  loop:
      - deploy.sh
      - manage.sh

- name: Set tag from the current image
  ansible.builtin.set_fact:
      release_tag: "{{ current_image.split(':')[1] }}"

- name: Run the deploy script to do Django migrations etc
  ansible.builtin.shell: |
      ./deploy.sh
  environment:
      TAG: "{{ release_tag }}"
