- name: Create deploy user
  ansible.builtin.user:
    name: "{{ user }}"
    createhome: yes
    state: present
- name: Create deploy directory
  ansible.builtin.file:
      path: "{{ project_dir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: "u+rw"
- name: Deploy SSH Key
  ansible.posix.authorized_key:
      user: "{{ user }}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      exclusive: true
      state: present
