- name: set environment variables
  dokku_config:
      app: "{{ appname }}"
      restart: false
      config:
          ADMIN_URL: "{{ admin_url }}"
          ADMINS: "{{ admins }}"
          ALLOWED_HOSTS: "{{ allowed_hosts }}"
          EMAIL_HOST: "{{ email_host }}"
          MAILGUN_API_KEY: "{{ mailgun_api_key }}"
          MAILGUN_API_URL: "{{ mailgun_api_url }}"
          SECRET_KEY: "{{ secret_key }}"
          SENTRY_URL: "{{ sentry_url }}"
