- name: set dokku app
  dokku_app:
      app: "{{ appname }}"
      state: present
- name: postgres:create
  dokku_service_create:
      name: "{{ postgres_service }}"
      service: postgres
- name: postgres:link
  dokku_service_link:
      app: "{{ appname }}"
      name: "{{ postgres_service }}"
      service: postgres
- name: redis:create
  dokku_service_create:
      name: "{{ redis_service }}"
      service: redis
- name: redis:link
  dokku_service_link:
      app: "{{ appname }}"
      name: "{{ redis_service }}"
      service: redis
- name: rebuild app
  dokku_clone:
      app: "{{ appname }}"
      repository: https://github.com/danjac/radiofeed-app
      version: main
      build: true
