- name: clear domains
  dokku_domains:
      app: "{{ appname }}"
      domains: "{{ appname }}.dokku.me"
      state: absent
- name: add domain
  dokku_domains:
      app: "{{ appname }}"
      domains: "{{ domain }}"
- name: set letsencrypt email and request certificate
  block:
      - name: set letsencrypt email
        ansible.builtin.shell: dokku letsencrypt:set {{ appname }} email {{ letsencrypt_email }}
        become: true
      - name: run letsencrypt
        dokku_letsencrypt:
            app: "{{ appname }}"
      - name: Schedule the dokku-letsencrypt auto renewal cron-job
        ansible.builtin.shell: "dokku letsencrypt:cron-job --add"
        become: true
