- name: Join swarm node
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['managers'][0]].swarm.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ "{{ hostvars[groups['managers'][0]].private_ip }}" ]
