- name: Set up user and docker on database
  hosts: database
  become: false
  remote_user: root
  vars:
      ansible_user: root
  roles:
      - user
      - docker

- name: Set up Postgresql and Redis
  hosts: database
  roles:
      - database
