- name: Provision K3s cluster
  hosts:
      - server
      - agents
  remote_user: root
  become: false
  vars:
      ansible_user: root
  roles:
      - user
      - k3s/cluster

- name: Set up server user with K3s access
  hosts: server
  remote_user: root
  become: false
  vars:
      ansible_user: root
  roles:
      - k3s/user

- name: Deploy application
  hosts: server
  become: false
  roles:
      - k3s/deploy
