- name: Install K3s
  hosts: kubernetes
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
  roles:
      - k3s_install

- name: Deploy application
  hosts: control_plane
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
      - vars/secrets.yml
  roles:
      - k3s_deploy

- name: Create deployment user
  hosts: control_plane
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
  roles:
      - user
      - k3s_user
