- name: Set up user and docker
  hosts: all
  become: true
  remote_user: root
  vars_files:
      - ./vars/settings.yml
  roles:
      - user
      - docker

- name: Set up Postgresql and Redis
  hosts: databases
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - databases

- name: Set up swarm managers and cronjobs
  hosts: managers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - managers
      - cron_schedulers

- name: Set up swarm workers
  hosts: workers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - workers

- name: Deploy stack
  hosts: managers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - deploy
