- name: Set up user and docker
  hosts: all
  become: false
  remote_user: root
  vars:
      ansible_user: root
  vars_files:
      - ./vars/config.yml
  roles:
      - user
      - docker

- name: Set up Postgresql and Redis
  hosts: database
  gather_facts: false
  vars_files:
      - ./vars/config.yml
      - ./vars/secrets.yml
  roles:
      - database

- name: Set up manager
  hosts: manager
  gather_facts: false
  vars_files:
      - ./vars/config.yml
      - ./vars/secrets.yml
  roles:
      - manager

- name: Set up workers
  hosts: workers
  gather_facts: false
  vars_files:
      - ./vars/config.yml
  roles:
      - workers

- name: Deploy stack
  hosts: manager
  gather_facts: false
  vars_files:
      - ./vars/config.yml
  roles:
      - deploy

- name: Set up cronjobs
  hosts: manager
  gather_facts: false
  vars_files:
      - ./vars/config.yml
  roles:
      - cron_scheduler
