- name: Set up user and docker on database
  hosts: database
  become: false
  remote_user: root
  vars:
      ansible_user: root
  vars_files:
      - ./vars/config.yml
  roles:
      - user
      - docker

- name: Set up Postgresql and Redis
  hosts: database
  vars_files:
      - ./vars/config.yml
      - ./vars/secrets.yml
  roles:
      - database

- name: Install K3s
  hosts:
      - server
      - agents
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
  roles:
      - k3s_install

- name: Deploy application
  hosts: server
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
      - vars/secrets.yml
  roles:
      - k3s_deploy

- name: Create deployment user
  hosts: server
  remote_user: root
  become: false
  vars:
      ansible_user: root
  vars_files:
      - vars/config.yml
  roles:
      - user
      - k3s_user
