- name: Remove old SSH keys and add new ones
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Remove old SSH keys from known_hosts
        ansible.builtin.known_hosts:
            name: "{{ item }}"
            state: absent
        loop: "{{ groups['all'] }}"

      - name: Scan and add new host keys
        ansible.builtin.shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
        loop: "{{ groups['all'] }}"
