repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
            exclude: ^static/dist
          - id: end-of-file-fixer
            exclude: ^static/dist
          - id: check-builtin-literals
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: destroyed-symlinks
          - id: detect-private-key
    - repo: https://github.com/ansible/ansible-lint
      rev: v24.6.1
      hooks:
          - id: ansible-lint
            additional_dependencies:
                - ansible
