- name: App server setup
  hosts: app_servers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/site.yml
    - ./vars/django.yml
  roles:
    - common
    - django
    - app_servers
