- name: Manager setup
  hosts: managers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/secrets.yml
    - ./vars/settings.yml
  roles:
    - common
    - managers

- name: Workers setup
  hosts: workers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/settings.yml
  roles:
    - workers
