- name: Cron scheduler setup
  hosts: cron_schedulers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/site.yml
    - ./vars/django.yml
  roles:
    - common
    - django
    - cron_schedulers
