- name: Postgresql and Redis setup
  hosts: databases
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/secrets.yml
    - ./vars/settings.yml
  roles:
    - common
    - databases
