- name: Postgresql and Redis setup
  hosts: databases
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
    - ./vars/site.yml
    - ./vars/postgresql.yml
  roles:
    - common
    - databases
