- name: User setup
  hosts: all
  become: true
  remote_user: root
  vars_files:
      - ./vars/settings.yml
  roles:
      - user

- name: Docker setup
  hosts: all
  become: true
  remote_user: root
  vars_files:
      - ./vars/settings.yml
  roles:
      - docker

- name: Postgresql and Redis setup
  hosts: databases
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - databases

- name: Swarm manager and crons setup
  hosts: managers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - managers
      - cron_schedulers

- name: Swarm workers setup
  hosts: workers
  remote_user: "{{ user }}"
  gather_facts: false
  vars_files:
      - ./vars/settings.yml
  roles:
      - workers
