- name: "Ubuntu server upgrades"
  hosts: all
  gather_facts: true
  become: true
  remote_user: root
  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists is true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true
