- name: Generate Docker swarm config file
  ansible.builtin.template:
    src: templates/deploy_stack.yml.j2
    dest: "{{ project_dir }}/stack.yml"
    mode: "u+rw,g+rw"
- name: Add script
  ansible.builtin.template:
    src: templates/stack.sh.j2
    dest: "/home/{{ user }}/deploy_stack.sh"
    mode: "u+x,g+x"
- name: Initialize Docker swarm
  community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ swarm_manager }}"
  register: swarm
- name: Deploy stack
  ansible.builtin.shell:
    cmd: ./deploy_stack.sh
