- name: Make sure pip installed
  apt:
    pkg:
      - python3
      - python3-pip

- name: Ensure python-docker installed
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
  shell: |
    pip3 install docker

- name: Prune containers older than 24h
  community.docker.docker_prune:
    containers: yes
    containers_filters:
      # only consider containers created more than 24 hours ago
      until: 24h
