- name: Add manage script
  ansible.builtin.template:
      src: manage.sh.j2
      dest: manage.sh
      mode: "u+x"

- name: Create log directory
  ansible.builtin.file:
      path: logs
      state: directory
      mode: "u+rw"

- name: Create log files
  ansible.builtin.file:
      path: "logs/{{ item }}.log"
      state: touch
      mode: "0666"
  loop: "{{ logs }}"

- name: Set up logrotate for cron logs
  remote_user: root
  vars:
      ansible_user: root
  ansible.builtin.template:
      src: logrotate.conf.j2
      dest: /etc/logrotate.d/{{ item }}
      mode: "0644"
  loop: "{{ logs }}"

- name: Install crontab
  vars:
      manage_cmd: ./manage.sh
      logs_dir: logs/
  block:
      - name: Install parse feeds cron
        ansible.builtin.cron:
            name: Parse feeds
            user: "{{ ansible_user }}"
            minute: "*/6"
            job: "{{ manage_cmd }} parse_feeds --limit=360 >> {{ logs_dir }}feedparser.log 2>&1"

      - name: Install create recommendations cron
        ansible.builtin.cron:
            name: Create recommendations
            user: "{{ ansible_user }}"
            minute: "20"
            hour: "6"
            job: "{{ manage_cmd }} create_recommendations >> {{ logs_dir }}recommendations.log 2>&1"

      - name: Install send recommendations emails cron
        ansible.builtin.cron:
            name: Send recommendations emails
            user: "{{ ansible_user }}"
            minute: "45"
            hour: "12"
            weekday: "1"
            job: "{{ manage_cmd }} send_recommendations >> {{ logs_dir }}emails.log 2>&1"

      - name: Install clear Django sessions cron
        ansible.builtin.cron:
            name: Clear Django sessions
            user: "{{ ansible_user }}"
            minute: "5"
            hour: "6"
            job: "{{ manage_cmd }} clearsessions >> {{ logs_dir }}clearsessions.log 2>&1"
