- name: Ensure we have the right vars
  debug:
    var: hostvars[groups['swarm_managers'][0]].swarm.swarm_facts.JoinTokens.Worker
- name: Join swarm node
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['swarm_managers'][0]].swarm.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ "{{ swarm_manager }}" ]
