- name: Copy docker-compose.yml
  ansible.builtin.template:
      src: docker-compose.j2
      dest: docker-compose.yml

- name: Add psql script
  ansible.builtin.copy:
      src: psql.sh
      dest: psql.sh
      mode: "u+x"

- name: Create PostgresSQL external volume
  community.docker.docker_volume:
      name: docker_pg_data

- name: Start Redis and PostgreSQL
  ansible.builtin.command:
      cmd: /usr/bin/docker compose up -d --remove-orphans
  changed_when: true

- name: Run Docker cleanup (optional)
  ansible.builtin.command:
      cmd: /usr/bin/docker system prune -f
  changed_when: true
