name: radiofeed_checks
on: workflow_call
jobs:
    precommit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12.6"
                  cache: "pip"
            - uses: pre-commit/action@v3.0.1
    unittests:
        needs: precommit
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_PASSWORD: password
                ports: ["5432:5432"]
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.12.6"
                cache: "pip"
            - run: pip install uv==0.4
            - run: uv pip install --all-extras
            - run: pyright
            - run: xargs -I{} python -c "import nltk; nltk.download('{}')" < ./nltk.txt
            - run: python -m pytest
