name: runchecks

on:
    workflow_call:

jobs:
    runchecks:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions

        services:
            postgres:
                image: postgres:14.1
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: github_actions
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v3.3.0
              with:
                  fetch-depth: 0

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11.1"
                  cache: pip

            - name: Install psycopg2 prerequisites
              run: sudo apt-get install libpq-dev

            - name: Install Python dependencies
              run: pip install -r requirements-ci.txt

            - name: Code quality checks
              run: |
                  python -m flake8 radiofeed

            - name: Security checks
              run: |
                  python -m bandit -r radiofeed -c pyproject.toml

            - name: Lint checks on Django templates
              run: |
                  python -m djlint --lint templates/

            - name: Run unit tests
              run: |
                  xargs python -m nltk.downloader < nltk.txt
                  python -m pytest
