name: Run CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions
      REDIS_URL: redis://localhost:4321
      SECRET_KEY: seekrit

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Typechecking
        run: |
          source .venv/bin/activate
          mypy radiofeed

      - name: Validate templates
        run: |
          source .venv/bin/activate
          python manage.py validate_templates

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          xargs python -m nltk.downloader < nltk.txt
          pytest -x
