name: radiofeed_cron_scheduler
on: workflow_call
jobs:
    deploy_cron_scheduler:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy to cron scheduler
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.CRON_SCHEDULER_IP }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ./deploy.sh
