name: radiofeed_deploy_docker
run-name: ${{ github.actor }} is building and pushing new Docker image
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    build_docker:
        needs: run_checks
        uses: ./.github/workflows/docker.yml
        secrets: inherit
