name: radiofeed_deploy_production
run-name: ${{ github.actor }} is deploying to production servers
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    build_docker:
        needs: run_checks
        uses: ./.github/workflows/docker.yml
        secrets: inherit
    deploy_stack:
        needs: build_docker
        uses: ./.github/workflows/stack.yml
        secrets: inherit
