name: deploy

on:
    workflow_dispatch:

jobs:
    # runchecks:
    #     uses: ./.github/workflows/checks.yml
    dokku:
        needs: runchecks
        # uses: ./.github/workflows/dokku.yml
        secrets:
            dokku_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
            dokku_private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
