name: deploy

on:
    workflow_dispatch:

jobs:
    runchecks:
        uses: ./.github/workflows/checks.yml
    dokku:
        needs: runchecks
        secrets: inherit
        uses: ./.github/workflows/dokku.yml
