name: radiofeed_deploy_production
run-name: ${{ github.actor }} is deploying to production servers
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    build_docker:
        needs: run_checks
        uses: ./.github/workflows/docker.yml
        secrets: inherit
    deploy_cron_scheduler:
        needs: build_docker
        uses: ./.github/workflows/cron_scheduler.yml
        secrets: inherit
    deploy_docker_swarm:
        needs: deploy_cron_scheduler
        uses: ./.github/workflows/docker_swarm.yml
        secrets: inherit
