name: radiofeed_deploy_docker
run-name: ${{ github.actor }} is deploying to app servers
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    build_docker:
        needs: run_checks
        uses: ./.github/workflows/docker.yml
        secrets: inherit
    deploy_app_servers:
        runs-on: ubuntu-latest
        needs: build_docker
        strategy:
            matrix:
                server_ip:
                    - APP_SERVER_1_IP
                    - APP_SERVER_2_IP
                    - APP_SERVER_3_IP
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Deploy to app server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets[matrix.server_ip] }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                    docker compose --project-directory ${{ secrets.PROJECT_DIR }} up -d --remove-orphans
                    docker system prune -f
