name: radiofeed_docker_swarm
on: workflow_call
jobs:
    deploy_docker_swarm:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to swarm manager
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SWARM_MANAGER_IP }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: ./deploy_stack.sh
