name: dokku-deployment

on:
    workflow_call:
        secrets:
            dokku_remote_url:
                required: true
            dokku_private_key:
                required: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Push to dokku
              uses: dokku/github-action@master
              with:
                  branch: main
                  trace: true
                  git_remote_url: ${{ secrets.dokku_remote_url }}
                  ssh_private_key: ${{ secrets.dokku_private_key }}
