name: dokku-deployment

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Push to dokku
              uses: dokku/github-action@master
              with:
                  git_remote_url: "ssh://dokku@radiofeed.app/radiofeed"
                  ssh_private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
                  branch: main
