name: listenwave_deploy_dokku
run-name: ${{ github.actor }} is deploying to Dokku
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    deploy:
        runs-on: ubuntu-latest
        needs: run_checks
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Push to dokku
              uses: dokku/github-action@master
              with:
                branch: main
                git_push_flags: --force
                git_remote_url: ${{ secrets.GIT_REMOTE_URL }}
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
