name: Run unit tests and deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  runtests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.create false
          python -m poetry install
          python -m nltk.downloader stopwords
          python -m nltk.downloader wordnet
      - name: Run unit tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions
          REDIS_URL: redis://localhost:4321
          SECRET_KEY: seekrit
        run: python -m pytest -x

  deploy:
    runs-on: ubuntu-latest
    needs: runtests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Dokku
        uses: dokku/github-action@master
        with:
          branch: main
          # git_remote_url: 'ssh://dokku@165.22.30.226:22/audiotrails'
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
