name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run test suite
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: docker-compose -f docker-compose.ci.yml run --rm django pytest

      - name: Build assets
        run: docker-compose -f docker-compose.ci.yml run --rm assets yarn build

      #- name: Store assets
      #uses: actions/upload-artifact@v2
      #with:
      #name: assets-dist
      #path: static/dist

      - name: Upload assets to S3
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        run: docker-compose -f docker-compose.ci.yml run --rm django collectstatic--noinput -v 3 -i dev -i src
