name: radiofeed_default
on: [pull_request, push]
run-name: ${{ github.actor }} is running checks
jobs:
    run_checks:
        uses: ./.github/workflows/checks.yml
    build_docker:
        needs: run_checks
        if: github.ref == 'refs/heads/main'
        uses: ./github/workflows/docker.yml
        secrets: inherit
