name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run test suite
        run: docker-compose -f docker-compose.ci.yml run --rm django pytest

      - name: Build assets
        run: docker-compose -f docker-compose.ci.yml run --rm assets yarn build

      # we might be able to deploy immediately to s3 without storing...
      - name: Store assets
        uses: actions/upload-artifact@v2
        with:
          name: assets-dist
          path: static/dist
