name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: radiofeed.config.settings.deploy
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build frontend assets
        run: docker-compose -f docker-compose.ci.yml run --rm assets yarn build

      - name: Upload assets to S3
        run: |
          docker-compose -f docker-compose.ci.yml run --rm django ./manage.py collectstatic --noinput -v 3 -i dev -i src

      - name: Push to Dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
