name: Run unit tests

on:
  push:
    branches:
      - develop
      - main

jobs:
  tests:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: psycopg2 prerequisites
        run: sudo apt-get install postgresql-client-11
      - name: Install dependencies
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.create false
          python -m poetry install
          python -m nltk.downloader stopwords
          python -m nltk.downloader wordnet
